# Generated by Django 4.2.13 on 2024-06-06 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
