# Generated by Django 4.2.13 on 2024-06-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_course_class_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
