# Generated by Django 4.2.13 on 2024-06-10 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_course_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='term',
            field=models.CharField(default='1245', max_length=100),
        ),
    ]
